apiVersion: v1
kind: ConfigMap
metadata:
  name: os-environment-variables
  namespace: {{.Values.kubernetes.platformnamespace}}
data:
  IS_MICROK8S_DEVELOPMENT_ENVIRONMENT: {{ if eq .Values.kubernetes.clustertype "microk8s" }}"true"{{ else }}"false"{{ end }}
  QP_PLATFORM_NAMESPACE: {{.Values.kubernetes.platformnamespace | quote}}
  QP_PLATFORM_VERSION: {{.Values.image.tag | quote}}

  DESIGN_GUNICORN_WORKER_COUNT: {{ .Values.appdesignconfig.gunicornworkercount  | squote }}

  RUNTIME_GUNICORN_WORKER_COUNT: {{ .Values.appruntimeconfig.gunicornworkercount  | squote }}

  DASHBOARD_MANAGER_GUNICORN_WORKER_COUNT: {{ .Values.dashboardconfig.gunicornworkercount  | squote }}

  CELERY_THREAD_COUNT: {{ .Values.appceleryworkerconfig.threadcount | default "10" | squote }}

  ALEMBIC_UPGRADE_OR_DOWNGRADE: {{ .Values.appdesignconfig.alembicupgradeordowngrade | default "upgrade" | quote }}
  ALEMBIC_REVISION_GUID: {{ .Values.appdesignconfig.alembicrevisionguid | default "head" | quote }}
  APP_RUNTIME_SERVICE: 'app-runtime-service'
  APP_DESIGN_SERVICE: 'app-design-service'
  DOCKERHUB_CREDS_SECRET_NAME: {{ .Values.dockerhub.secretname | quote  }}
  #NEW_RELIC_ENVIRONMENT: 'SECRET'
  #QP_APP_DB_NAME: 'SECRET'
  QP_APP_DB_HOST: {{ .Values.mysql.databasehost | quote}}
  QP_APP_DB_PORT: {{ .Values.mysql.databaseport | quote}}
  #QP_APP_DB_USERNAME: 'SECRET'
  #QP_APP_DB_PASSWORD: 'SECRET'
  QP_APP_ASYNC_BROKER_URL: {{ .Values.redis.host }}
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ ((.Values).redis).port  | default "6379" | quote }}
  #REDIS_PASSWORD: 'SECRET'

  APP_DESIGN_LOG_CONSOLE_LEVEL: {{ .Values.appdesignconfig.logconsolelevel | quote}}
  APP_DESIGN_LOG_FILE_LEVEL: {{ .Values.appdesignconfig.logfilelevel | quote}}

  APP_RUNTIME_LOG_CONSOLE_LEVEL: {{ .Values.appruntimeconfig.logconsolelevel | quote}}
  APP_RUNTIME_LOG_FILE_LEVEL: {{ .Values.appruntimeconfig.logfilelevel | quote}}

  APP_CELERY_WORKER_LOG_CONSOLE_LEVEL: {{ .Values.appceleryworkerconfig.logconsolelevel | quote}}
  
  APP_DASHBOARD_MANAGER_LOG_CONSOLE_LEVEL: {{ .Values.dashboardconfig.logconsolelevel | quote}}
  APP_DASHBOARD_MANAGER_LOG_FILE_LEVEL: {{ .Values.dashboardconfig.logfilelevel | quote}}

  APP_SCHEDULER_LOG_CONSOLE_LEVEL: {{ .Values.schedulerconfig.logconsolelevel | quote}}
  APP_SCHEDULER_LOG_FILE_LEVEL: {{ .Values.schedulerconfig.logfilelevel | quote}}

  APP_SUBSCRIPTION_MANAGER_LOG_CONSOLE_LEVEL: {{ .Values.subscriptionconfig.logconsolelevel | quote}}
  APP_SUBSCRIPTION_MANAGER_LOG_FILE_LEVEL: {{ .Values.subscriptionconfig.logfilelevel | quote}}

  APP_SQLALCHEMY_LOG_LEVEL: {{ .Values.appdesignconfig.sqlalchemyloglevel| default "WARNING" | quote}}
  APP_ROOT_LOG_LEVEL: {{ .Values.appdesignconfig.rootloglevel| default "WARNING" | quote}}

  USE_VOLUME_MOUNT_SECRETS: {{ ((.Values).secrets).useVolumeMountSecrets | default "false" | quote }}

  #QP_APP_SECRET_KEY: 'SECRET'
  SECRETS_MANAGER_TYPE: {{ .Values.secretsmanager.managertype }}
  SECRETS_AWS_INSTANCE_PREFIX: {{ .Values.secretsmanager.instanceprefix | quote}}

  SECRETS_AWS_REGION_NAME: {{ ((.Values).secretsmanager).regionname | default "" | quote}}
  SECRETS_AWS_CACHING_ENABLED: {{ ((.Values).secretsmanager).secretcachingenabled | default "" | quote }}
  #SECRETS_AWS_ACCESS_KEY_ID: 'SECRET'
  #SECRET_AWS_SECRET_ACCESS_KEY: 'SECRET'

  SECRETS_AZURE_VAULT_URL: {{ ((.Values).secretsmanager).azurevaulturl | default "" | quote}}
  #SECETS_AZURE_TENANT: 'SECRET'
  #SECETS_AZURE_CLIENT_ID: 'SECRET'
  #SECRETS_AZURE_CLIENT_SECRET: 'SECRET'


  IS_BASIC_AUTH_ENABLED: {{ .Values.basicauth.enabled | quote }}
  BASIC_AUTH_EXPIRATION_MINUTES: {{ .Values.basicauth.expirationminutes | default "720" | quote }}

  MSAL_PLATFORM_BASE_URL: {{ ((.Values).msal).platformbaseurl | default "" | quote}}
  MSAL_TENANT_ID: {{ ((.Values).msal).tenantid | default "" | quote}}
  MSAL_CLIENT_ID: {{ ((.Values).msal).clientid | default "" | quote}}
  #MSAL_CLIENT_SECRET: 'SECRET'

  GOOGLE_PLATFORM_BASE_URL: {{ ((.Values).googleauth).platformbaseurl | default "" | quote}}

  OPENAI_MODEL_ID: {{ ((.Values).openai).modelid | default "" | quote}}

  GENERATIVE_AI_BACKEND: {{ ((.Values).ai).backend | default "" | quote }}

  AMAZON_BEDROCK_AWS_REGION_NAME: {{ ((.Values).bedrock).aws_region_name | default "" | quote }}
  AMAZON_BEDROCK_MODEL_ID: {{ ((.Values).bedrock).model_id | default "" | quote }}