---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.dockerhub.secretname}}
  namespace: {{.Values.kubernetes.platformnamespace}}
type: kubernetes.io/dockerconfigjson
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials
  .dockerconfigjson: {{.Values.dockerhub.dockerfilejson}}




{{ if eq .Values.secrets.useExternalSecrets "true" }}

{{- if .Values.secrets.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qpp-eso
  namespace: {{ .Values.kubernetes.platformnamespace }}
  {{- with .Values.secrets.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{ if .Values.secrets.auth.accessKeyID }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{.Values.kubernetes.platformnamespace}}
data:
  SECRETS_AWS_ACCESS_KEY_ID: {{.Values.secrets.auth.accessKeyID | b64enc }}
  SECRET_AWS_SECRET_ACCESS_KEY: {{.Values.secrets.auth.secretAccessKey | b64enc }}
{{ end }}



---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: qp-ext-secret-store
  namespace: {{ .Values.kubernetes.platformnamespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
      {{ if .Values.secrets.auth.accessKeyID }}
        secretRef:
          accessKeyIDSecretRef:
                name: aws-credentials
                key: SECRETS_AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
                name: aws-credentials
                key: SECRET_AWS_SECRET_ACCESS_KEY
      {{ else }}
        jwt:
          serviceAccountRef:
            name: qpp-eso
      {{ end }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qp-ext-secret
  namespace: {{ .Values.kubernetes.platformnamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: qp-ext-secret-store
    kind: SecretStore
  target:
    name: app
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: .dockerconfigjson
  - secretKey: QP_APP_SECRET_KEY
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: APP_SECRET_KEY
  - secretKey: NEWRELIC_LICENSE_KEY
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: NEWRELIC_LICENSE_KEY
  - secretKey: SECRETS_AWS_ACCESS_KEY_ID
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AWS_SECRETSMANAGER_ACCESS_KEY_ID
  - secretKey: SECRET_AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AWS_SECRETSMANAGER_SECRET_ACCESS_KEY
  - secretKey: SECETS_AZURE_TENANT
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AZURE_SECRETSMANAGER_TENANT
  - secretKey: SECETS_AZURE_CLIENT_ID
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AZURE_SECRETSMANAGER_CLIENT_ID
  - secretKey: SECRETS_AZURE_CLIENT_SECRET
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AZURE_SECRETSMANAGER_CLIENT_SECRET
  - secretKey: SECRETS_GOOGLE_SERVICE_ACCOUNT_JSON
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: GOOGLE_SECRETSMANAGER_SERVICE_ACCOUNT_JSON
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: OPENAI_API_KEY
  - secretKey: QP_APP_DB_NAME
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: APP_DB_NAME
  - secretKey: QP_APP_DB_USERNAME
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: APP_DB_USERNAME
  - secretKey: QP_APP_DB_PASSWORD 
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: APP_DB_PASSWORD
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: REDIS_PASSWORD
  # - secretKey: MSAL_CLIENT_ID
  #   remoteRef:
  #     key: {{ .Values.secrets.externalSecretPath }}
  #     property: AUTH_MICROSOFT_CLIENT_ID
  # - secretKey: MSAL_TENANT_ID
  #   remoteRef:
  #     key: {{ .Values.secrets.externalSecretPath }}
  #     property: AUTH_MICROSOFT_TENANT_ID
  - secretKey: MSAL_CLIENT_SECRET
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AUTH_MICROSOFT_CLIENT_SECRET
  - secretKey: GOOGLE_OAUTH_CLIENT_ID
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AUTH_GOOGLE_CLIENT_ID
  - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
    remoteRef:
      key: {{ .Values.secrets.externalSecretPath }}
      property: AUTH_GOOGLE_CLIENT_SECRET  




{{ else }}
##################################################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: {{.Values.kubernetes.platformnamespace}}
data:
  QP_APP_SECRET_KEY: {{.Values.appdesignconfig.sessionsecret}}
  NEWRELIC_LICENSE_KEY: {{ ((.Values).newrelic).licensekey | default "" | quote }}
  SECRETS_AWS_ACCESS_KEY_ID: {{ ((.Values).secretsmanager).accesskeyid | default "" | quote }}
  SECRET_AWS_SECRET_ACCESS_KEY: {{ ((.Values).secretsmanager).secretaccesskey | default | quote }}
  SECETS_AZURE_TENANT: {{ ((.Values).secretsmanager).azuretenant | default "" | quote }}
  SECETS_AZURE_CLIENT_ID: {{ ((.Values).secretsmanager).azureclientid | default "" | quote }}
  SECRETS_AZURE_CLIENT_SECRET: {{ ((.Values).secretsmanager).azureclientsecret | default "" | quote }}
  SECRETS_GOOGLE_SERVICE_ACCOUNT_JSON: {{ ((.Values).secretsmanager).googleserviceaccountjson | default "" | quote }}
  OPENAI_API_KEY: {{ ((.Values).openai).apikey | default "" | quote }}
  QP_APP_DB_NAME: {{.Values.mysql.databasename}}
  QP_APP_DB_USERNAME: {{.Values.mysql.databaseuser}}
  QP_APP_DB_PASSWORD: {{.Values.mysql.databasepassword}}
  REDIS_PASSWORD: {{.Values.redis.password | default "" | quote }}
  MSAL_CLIENT_SECRET: {{ ((.Values).msal).clientsecret | default "" | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ ((.Values).googleauth).google_oauth_client_id | default "" | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ ((.Values).googleauth).google_oauth_client_secret | default "" | quote }}
{{ end }}

