---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Values.kubernetes.storagename | default "app-storage" | quote}}
  namespace: {{.Values.kubernetes.platformnamespace}}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
{{- if eq .Values.kubernetes.clustertype "microk8s" }}
provisioner: microk8s.io/hostpath
{{- end }}
{{- if eq .Values.kubernetes.clustertype "eks" }}
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
{{- end }}
{{- if eq .Values.kubernetes.clustertype "gks" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
{{- end }}
{{- if eq .Values.kubernetes.clustertype "aks" }}
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
provisioner: kubernetes.io/azure-disk
{{- end }}
reclaimPolicy: Retain
volumeBindingMode: Immediate