apiVersion: v2
name: QPP-chart
description: Quickpath Platform Helm Chart
type: application
version: "2.4.6"
appVersion: "2.4.6"
dependencies:
  - name: mysql
    version: "9.23.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.helm_deployment_enabled
  - name: redis
    version: "18.19.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.helm_deployment_enabled
  - name: qdrant
    version: "0.8.4"
    repository: "https://qdrant.to/helm"
    condition: qdrant.helm_deployment_enabled